version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ../src/ui
    image: ${UserName}/ui:${UI_VERSION}
    ports:
      - ${PUBLIC_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front:
        aliases:
          - ui



  post:
    build: ../src/post-py
    image: ${UserName}/post:${POST_VERSION}
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back:
        aliases:
          - post
      front:
        aliases:
          - post


  comment:
    build: ../src/comment
    image: ${UserName}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back:
        aliases:
          - comment
      front:
        aliases:
          - comment


  prometheus:
    image: ${UserName}/prometheus
    ports:
      - '9090:9090'
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back:
      front:
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день



  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /:/rootfs:ro
    networks:
      back:
      front:
    command:
       - '--path.procfs=/host/proc'
       - '--path.sysfs=/host/sys'
       - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


       
volumes:
  post_db:
  prometheus_data:
  posts:

networks:
  back:
  front:
